# Generated by Django 3.2 on 2023-10-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_rename_lessonviesinfo_lessonviewinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonviewinfo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lessonviewinfo',
            constraint=models.UniqueConstraint(fields=('lesson', 'user'), name='unique_pair'),
        ),
    ]
