# Generated by Django 4.0 on 2023-10-13 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20231010_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonviewinfo',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 11, 17, 48, 670678)),
        ),
    ]
