# Generated by Django 4.0 on 2023-10-13 11:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_lessonviewinfo_last_view_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonviewinfo',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 11, 23, 50, 253073)),
        ),
    ]
