# Generated by Django 3.2 on 2023-10-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20231006_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonView',
        ),
    ]
