# Generated by Django 3.2 on 2023-10-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
